FROM node:20-alpine AS builder
WORKDIR /app
COPY backend/package.json backend/package-lock.json* ./ 
RUN npm install
COPY prisma ./prisma
COPY backend ./ 
RUN npx prisma generate --schema prisma/schema.prisma
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY backend/package.json ./package.json
RUN npm install --only=production
CMD ["node", "dist/index.js"]
